@startuml

title Activity Diagram 

start

:User provides sleep parameters; 
:Program checks sleep parameters;

if (Is Data Correct?) then (yes)
  :Data is correct!;
else (no)
  :Your data is incorrect, check your data!;
endif

stop

@enduml
